<template>
  <button 
    type="button" 
    class="
      w-full 
      border-l border-b border-t border-gray-300 
      px-4 
      py-2 
      bg-white 
      text-base 
      font-bold
      text-gray-700 
      hover:bg-gray-200
      hover:border-transparent
      focus:bg-teal
      focus:text-teal-lighter
      focus:border-transparent">
    <slot></slot>
  </button>
</template>
