<template>
  <select 
    class="
      inline-flex
      w-full
      justify-center 
      rounded-md
      shadow-sm
      px-3
      py-2 
      bg-white 
      text-base 
      font-medium 
      text-teal
      focus:outline-none 
      focus:ring
      focus:ring-offset-2 
      focus:ring-offset-white 
      focus:ring-teal-light 
      border border-gray-500">
    <slot></slot>
  </select>
</template>
