<template>
  <li>
    <div>
      <button
        type="button"
        class="
          group
          relative
          inline-flex
          cursor-pointer
          rounded-md
          px-4
          py-2
          text-base
          font-medium
          text-gray-700
          hover:text-white hover:bg-teal
        "
      >
        <slot></slot>
      </button>
    </div>
  </li>
</template>
