<template>
  <li 
    class="
      px-3 
      py-2 
      text-gray-600 
      font-normal  
      flex-nowrap 
      text-base
      hover:underline 
      hover:bg-gray-200">
    <slot></slot>
  </li>
</template>